"""js/world-mask.js uretici.

Acilis haritasinin kara maskesini, ilk uretilen js/world-dots.js koordinat
listesinden turetir: her noktanin cevresinde 3.5 birimlik disk birlesimi kara
alani verir, bu alan yari aralikli izgarayla yeniden orneklenir. Cikti koordinat
listesi degil, hucre basina bir bit (base64) — ~240 KB yerine ~11 KB.

Sayfaya giden tek nokta verisi budur: ince doku maskenin kendisi, kaba doku ise
her ikinci hucresi (tam olarak eski koordinat listesinin izgarasi). Kaynak dosya
js/world-dots.js depoda kalir ama tarayiciya yuklenmez.

Kullanim: depo kokunde `python3 tools/gen_world_dots_fine.py`
"""

import re, io, math, base64
from collections import defaultdict

src = io.open("js/world-dots.js", encoding="utf-8").read()
nums = [float(x) for x in re.findall(r'-?\d+\.?\d*', src.split('=',1)[1])]
pts = list(zip(nums[0::2], nums[1::2]))

R, CELL = 3.5, 8.0
buck = defaultdict(list)
for x, y in pts: buck[(int(x // CELL), int(y // CELL))].append((x, y))
def is_land(px, py):
    cx, cy, r2 = int(px // CELL), int(py // CELL), R * R
    for i in (cx-1, cx, cx+1):
        for j in (cy-1, cy, cy+1):
            for x, y in buck.get((i, j), ()):
                if (x-px)**2 + (y-py)**2 <= r2: return True
    return False

X0, Y0, SX, SY = 10.0, 24.0, 5.2/2, 4.625/2
COLS = int((998.0 - X0) / SX) + 1
ROWS = int((398.0 - Y0) / SY) + 1
bits = bytearray((COLS * ROWS + 7) // 8)
n = 0
for row in range(ROWS):
    y = Y0 + row * SY
    ox = SX / 2 if row % 2 else 0.0
    for col in range(COLS):
        x = X0 + ox + col * SX
        if x <= 998.0 and is_land(x, y):
            i = row * COLS + col
            bits[i >> 3] |= 1 << (i & 7)
            n += 1
b64 = base64.b64encode(bytes(bits)).decode()
out = f"""// Land mask for the opening world map — the only dot data the page loads.
// Generated by tools/gen_world_mask.py; do not hand-edit.
//
// One bit per lattice cell instead of coordinates: the fine fabric is {n} dots,
// which would be ~240 KB as x,y pairs against {len(b64)//1024} KB here. Both
// fabrics come out of this one mask — the fine one is the lattice itself, the
// coarse one every second cell of it (exactly the lattice the original
// coordinate list used). See renderWorldDots() in app.js.
const WORLD_MASK = {{
  x0: {X0}, y0: {Y0}, sx: {SX}, sy: {SY}, cols: {COLS}, rows: {ROWS},
  bits: "{b64}"
}};
"""
io.open("js/world-mask.js", "w", encoding="utf-8").write(out)
print(f"{n} nokta, izgara {COLS}x{ROWS}, base64 {len(b64)/1024:.1f} KB")
